### ISSUE TITLE
Upgraded to ember-rails (0.7.0), stopped working.

### ISSUE THREAD

**Issue by jcoyne** [dgeb/ember_data_example#11]
I removed app/assets/javascripts/vendor and made the following change to app/assets/javascripts/application.js:

<pre>
-//= require ./vendor/ember
-//= require ./vendor/ember-data
+//= require handlebars
+//= require ember
+//= require ember-data
</pre>

**Comment by dgeb** [comment]
I'm sorry for the delay in getting back to you. This example was originally written 9 months ago and is no longer compatible with the latest versions of ember and ember-data. Therefore, commenting out the old versions, which were kept in /vendor, and going with the versions provided by ember-rails would certainly lead to problems.

With that said, I'm in the process of revisiting this example to be compatible with the edge versions of ember and ember-data. It should be much more up-to-date and useful soon.
