### ISSUE TITLE
Add tests for Ember application

### ISSUE THREAD

**Issue by pangratz** [dgeb/ember_data_example#26]
I think it would be neat if this wonderful sample repository would illustrate how to test the Ember application. I'm not very experienced with Rails so I don't know exactly where to put JS tests.

I just wanted to open this issue to start a discussion. Any ideas?

**Comment by dgeb** [comment]
@pangratz definitely a good idea - thanks for filing the issue! I'm planning to use konacha to test this example with mocha / chai. I had been waiting until after the router refactor, but thankfully that's done now :)

**Comment by lulezi** [comment]
Having tests in here would be great! I'm not experienced with testing in Ember at all so that'd be a great starting point.

**Comment by pangratz** [comment]
@dgeb I have used konacha in one of the Rails apps I am developing the JS app for. I'm just curious whether there is an "official" way of JS testing?

If you're plans are to use konacha anyway, I'm happy to create a PR for that ...

**Comment by dgeb** [comment]
@pangratz that would be great if you send a PR to bring in konacha. Thanks!

**Comment by pangratz** [comment]
I've opened a pull request, let's move the discussion ...
