### ISSUE TITLE
Update spec_helper and acceptance test examples

### ISSUE THREAD

**Issue by ulisesrmzroche** [dgeb/ember_data_example#38]
Updating the example specs to accommodate for both unit and acceptance tests, and  having test_helper use App.reset() instead of deferring and advancing app readiness would be awesome. I've got a good weekend to do this if I can help.

**Comment by sly7-7** [comment]
definitely do it :). I've said to @dgeb I would do it something like 10 days ago. Unfortunately, I've not taken the time to do this.

**Comment by dgeb** [comment]
@ulisesrmzroche The test_helper actually is using `App.reset()` in the [`afterEach`](https://github.com/dgeb/ember_data_example/blob/master/test/javascripts/test_helper.js#L58). I used to use it in my `beforeEach`, but adjusted the approach with recent changes to Ember's app initialization. Regardless, I would like to update the test suite to accommodate both unit and acceptance tests, and any help would be appreciated. Thanks in advance!

@sly7-7 no worries - you've helped a ton with this project already!

**Comment by dgeb** [comment]
Closing this now, even though I've still got more tests to write. Thanks to you both (@ulisesrmzroche and @sly7-7) for your help getting this started!
