### ISSUE TITLE
linecache and ruby-debug-base gem versions are too recent

### ISSUE THREAD

**Issue by jackdempsey** [dgeb/ember_data_example#4]
Could not find linecache19-0.5.13 in any of the sources
Could not find ruby-debug-base19-0.11.26 in any of the sources

Changing the Gemfile.lock to use linecache19-0.5.12 and ruby-debug-base19-0.11.25  let me bundle correctly.

**Comment by jackdempsey** [comment]
Looks like this is intentional. Adding link to help explain/give backstory: http://stackoverflow.com/questions/7054948/ruby-debug19-on-ruby-1-9-3-preview1

**Comment by dgeb** [comment]
Yep, I had to jump through some hoops to get ruby-debug working for 1.9.3.
