### ISSUE TITLE
workflow bug

### ISSUE THREAD

**Issue by Daniel-Xu** [dgeb/ember_data_example#41]
1  click "add new contact" , then edit interface shows

2 then click "all contact"  at left side , then a bug shows

**Comment by sly7-7** [comment]
Just to confirm, by bug, you mean that the new contact appears in the list, right ?

**Comment by dgeb** [comment]
I'm going to close this for now, but please re-open if you can be more specific about the nature of the bug.

**Comment by Daniel-Xu** [comment]
@sly7-7  yes, I mean the new contact appear in the list , and can click the "edit" and "remove" button although it doesn't work. 

In my opinion, when contact is not saved, it shouldn't be a link! 

@dgeb

**Comment by dgeb** [comment]
@Daniel-Xu - Thanks for clarifying. I'll re-open this and consider removing the new contact from the listing until it's been saved.

**Comment by dgeb** [comment]
After reviewing the interface, I decided to filter the contact array to exclude new ones. Thanks for pointing this out @Daniel-Xu

**Comment by Daniel-Xu** [comment]
I see the code, thanks for this project to let me start learning ember !

**Comment by Daniel-Xu** [comment]
@dgeb  hello  I try to rewrite  this project using coffee script, but I got stuck in getting data from server, could I get contact with through skype or any thing?

**Comment by dgeb** [comment]
@Daniel-Xu I'd recommend translating one file at a time from JS to CS and testing as you go. This should help you pinpoint your issue.
