### ISSUE TITLE
Bundle install fails because of ruby-debug19

### ISSUE THREAD

**Issue by mrs** [dgeb/ember_data_example#9]
It depends on linecache19-0.5.13, which can't be found.

**Comment by dgeb** [comment]
The debugging situation is a mess in Ruby 1.9.3. See http://blog.wyeworks.com/2011/11/1/ruby-1-9-3-and-ruby-debug for details and how to install linecache19-0.5.13. You could also switch to the new `debugger` gem.

**Comment by dgeb** [comment]
I decided to just remove the ruby-debug dependency to minimize confusion over the whole 1.9.3 / debug / linecache mess.
